### ISSUE TITLE
Missing # in styling by element id 'label-studio'

### ISSUE THREAD

**Issue by adriantre** [asehmi/streamlit-label-studio-frontend#1]
```css
  #label-studio {
    height: calc(100vh - 88px);
  }
```

https://github.com/asehmi/streamlit-label-studio-frontend/blob/1202bf42bc60bb149d3126359be574cc22b2e0cc/frontend/index.html#L22
